.PHONY: clean All

All:
	@echo "----------Building project:[ gpio-client - Debug ]----------"
	@cd "/var/www/OrangePiWeb/gpio-client" && "$(MAKE)" -f  "gpio-client.mk"
clean:
	@echo "----------Cleaning project:[ gpio-client - Debug ]----------"
	@cd "/var/www/OrangePiWeb/gpio-client" && "$(MAKE)" -f  "gpio-client.mk" clean
