.PHONY: clean All

All:
	@echo "----------Building project:[ gpio-server - Debug ]----------"
	@cd "gpio-server" && "$(MAKE)" -f  "gpio-server.mk"
clean:
	@echo "----------Cleaning project:[ gpio-server - Debug ]----------"
	@cd "gpio-server" && "$(MAKE)" -f  "gpio-server.mk" clean
